name: cryptowatch_candle_chart
description: A Flutter K Chart.
version: 0.1.2
homepage: https://github.com/mafanwei/k_chart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter